seq = 'AGACCCTGTCACCCCTCCCACTTGGTTATGGCTTTTAACCTTTAGATGTCGTGGGTGTCTTAGAGTCTGTAGCCCACCAATTGCGCAGAGACCGTACTAAAAGGCCCCGAAACACGTTATTATGATCACACCTTCATGTGGAGAGTACTTTCGCTGGTGTGCCAAAATGGACGCAGAGATATAGTCGAGGGACCTATTGTGACAGGGCATGCCACCAGCTAGACTACCGAGTAGTAGATTTGCCGCACGCACGTGCACTTGTTATCGCCTGGCTTGCACAAGACAAAACCTGCGTACCTGTGTACCGAGAATTACCTTGACGGTCCCCTGCTTCTAACAAAGTTGCATCATATTCAAGAGTGGCCGTGCCCCCGGTCTACTTTCCGAAGACACTGGTCCACCGGAAGACAGGTGCAAATATGGCGTGAGTGGCCAAGCTTGGAAGCAGGGATCGCCTTTTTCAAACGATCAAAAGAGACTTAAAGTCGAAGTGGGCCAGCTATAGCCACACCAAGACTTCTCAGTCGGTGTTGCTGTTAAAGGACATAGGGTGGAGTAAGTCCGCAGAGCAGCTCGAATTTGACACTCCAGGTCTGCCCTATAACTGTGTTTGGTTTCCAGCCCACTTGCCGTCCCATACCGCTCTGGAGCTCCGAAACCGTCTGCACTCAGTGCCATGTTGTCGCTCAGATCCTACGGATTACTCTAGTCGTTAGGTCAAGTTTGGCTAGCCTCTACCCAACCCTATCACTGTTTCGCTCTTCATAAGCACCGCGGACGAGCGCGTGCATTCACGCCAGCCGCAAGTTTACCACCAGGAGTTCAGGGATACTGTTCCAACATGCTAT'
a = 0
g = 0
t = 0
c = 0

for i in range(len(seq)):
    if seq[i]=='A':
        a = a + 1
    if seq[i]=='T':
        t = t + 1
    if seq[i]=='G':
        g = g + 1
    if seq[i]=='C':
        c = c + 1

print(str(a) + ' ' + str(c) + ' ' + str(g) + ' ' + str(t))